### ISSUE TITLE
 There are some problems building VMosc.

### ISSUE THREAD

**Issue by WTactic** [techlemur/VMosc#3]
**There are some problems building VMosc. Ethan, could you post a release?**

![image](https://user-images.githubusercontent.com/40234517/90330911-2a4f3800-dfb9-11ea-9a10-ae0bf680bcfd.png)
![image](https://user-images.githubusercontent.com/40234517/90330913-30ddaf80-dfb9-11ea-8e4c-b35db34c978e.png)

**Comment by techlemur** [comment]
@WildTactic - Try [this](/techlemur/VMosc/releases/tag/v0.0-alpha)

**Comment by WTactic** [comment]
@techlemur Thanks, Ethan.

**Comment by techlemur** [comment]
@WildTactic  Did that work for you?

**Comment by techlemur** [comment]
c283e6e4715f2efaf10a052490eb456a76c4944d should fix the build issue.
