### ISSUE TITLE
Can't get feedback on port 9000

### ISSUE THREAD

**Issue by Vodianoi** [techlemur/VMosc#4]
Hi !

I'm using TouchOSC on an iPad and Voicemeeter on my Desktop.
I can send messages from the iPad to Voicemeeter, but I get no feedback from Voicemeeter on port 9000 (even if it is sending one : the midi output is triggered in Voicemeeter)

I tried using the TouchOSC Windows app : same result

I also tried to build from source but they are missing ressource files in the repository apparently.

Am i missing something or it is not implemented ?

Thank you !

**Comment by techlemur** [comment]
@Vodianoi 
- Have you checked the port settings in TouchOSC in the iPad?
- Which version of Voicemeeter are you using?
- Are any of the remote indicators at the top left of Voicemeeter lit up? 
![image](https://user-images.githubusercontent.com/34924313/125996644-fbb73ad6-3b85-4b5f-930d-772122fe0c32.png)

**Comment by Vodianoi** [comment]
Thanks for answering, 

Yes I checked the port, it seems correct I think
![GitHawk Upload by Vodianoi](https://i.imgur.com/4y67Snc.jpg)

I use Potato and the app is correctly linked (I have the remote icons on) 

Maybe a firewall is blocking something since it is working one way...
I tried on different devices though.

Any clues?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by techlemur** [comment]
@Vodianoi 
Turns out I had hard coded the broadcast address to my network setup.  :man_facepalming:
Please try the new release and let me know if it works. 

https://github.com/techlemur/VMosc/releases/tag/v0.1-beta

**Comment by Vodianoi** [comment]
Nice, it's working perfectly now! I see you updated the repo too !
Thank you very much !
